name: Merge Design Tokens

on:
  push:
    branches: [dev]
    paths:
      - "tokens/**"
      - "src/merge-tokens.js"
  workflow_dispatch:

jobs:
  merge-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Merge tokens
        run: npm run merge:tokens

      - name: Upload merged tokens as artifact
        uses: actions/upload-artifact@v4
        with:
          name: merged-tokens
          path: dist/merged-tokens.json